Cypress.Commands.add ("login", (name, email, password, days, months, years, first_name, last_name, company,
address, address2, country, state, city, zipcode, mobile_number) =>{        
    cy.contains ("Category").should("be.visible")
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.signup-form > h2').should("have.text", "New User Signup!")
    cy.get('[data-qa="signup-name"]').type(name)  
    cy.get('[data-qa="signup-email"]').type(email) 
    cy.get('[data-qa="signup-button"]').click()
    cy.contains ("Enter Account Information").should("be.visible")
    cy.get('#id_gender2').click()
    cy.get('[data-qa="password"]').type(password) 
    cy.get('[data-qa="days"]').select(days) 
    cy.get('[data-qa="months"]').select(months) 
    cy.get('[data-qa="years"]').select(years)
    cy.get('#newsletter').check()
    cy.get('#optin').check()
    cy.get('[data-qa="first_name"]').type(first_name) 
    cy.get('[data-qa="last_name"]').type(last_name) 
    cy.get('[data-qa="company"]').type(company) 
    cy.get('[data-qa="address"]').type(address) 
    cy.get('[data-qa="address2"]').type(address2) 
    cy.get('[data-qa="country"]').select(country) 
    cy.get('[data-qa="state"]').type(state) 
    cy.get('[data-qa="city"]').type(city) 
    cy.get('[data-qa="zipcode"]').type(zipcode) 
    cy.get('[data-qa="mobile_number"]').type(mobile_number)
    cy.get('[data-qa="create-account"]').click()
    cy.get('b').should("be.visible")
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should("be.visible") })